# Generated by Django 4.2.1 on 2023-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='medicines',
            name='date_issue',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Дата выпуска'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='expiry_date',
            field=models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название препарата'),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='requisites_sup',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='сustomer',
            name='requisites_cust',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
