# Generated by Django 4.2.1 on 2023-05-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_pharmacy_medicines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='medicines_as_pharmacy', to='core.medicines'),
        ),
    ]
